name: Tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  # Linux, Windows, MacOS
  test-standard:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12', '3.13', '3.14', '3.14t']

    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Rust
        run: rustup update stable && rustup default stable
        
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: pip install maturin polars

      # - name: Start Server
      #   shell: bash
      #   run: python src/mock_server.py

      - name: Build Rust library and install
        shell: bash
        run: |
          maturin build --release
          pip install target/wheels/*.whl

      - name: Run tests
        run: |
          cd tests
          python -m unittest discover .

  # Alpine Linux (Musl) 
  test-alpine:
    name: Test (Alpine/Musl)
    runs-on: ubuntu-latest
    container:
      image: python:3.13-alpine
    steps:
      - uses: actions/checkout@v6
      - name: Install Alpine build deps
        run: apk add --no-cache clang clang-dev gcc g++ make cmake musl-dev cargo git patchelf

      - name: Install dependencies
        run: pip install maturin polars
      
      # - name: Start Server
      #   run: python src/mock_server.py
      
      - name: Build Rust library and install
        run: |
          maturin build --release
          pip install target/wheels/*.whl

      - name: Run tests
        run: |
          cd tests
          python -m unittest discover .

  # FreeBSD 
  # waiting for py313-polars, as there is no official wheel
  # test-freebsd:
  #   name: Test (FreeBSD)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Test in FreeBSD VM
  #       uses: vmactions/freebsd-vm@v1
  #       with:
  #         usesh: true
  #         prepare: pkg install -y rust python313 py313-polars git
  #         run: |
  #           python3.13 -m venv venv
  #           . venv/bin/activate
  #           pip install maturin polars
  #           maturin build --release
  #           pip install target/wheels/*.whl
  #           # python src/mock_server.py
  #           cd tests
  #           python -m unittest discover .
